openapi: 3.0.0
info:
  title: Play it with us
  version: 0.1.0

servers:
  - url: http://piwu.example.com/
    description: Production

paths:
  /clubs:
    post:
      summary: Register a new club
      tags: ['Club Directory']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterClub'
      responses:
        200:
          description: A JSON array of clubs

    get:
      summary: Get all the clubs
      tags: ['Club Directory']
      responses:
        200:
          description: A JSON array of clubs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
              examples:
                Tom:
                  value:
                    - id: 1
                      name: Tom's Awesome Club
                    - id: 2
                      name: Tom's Brilliant Club
                Chris:
                  value:
                    - id: 1
                      name: Chris's Awesome Club
                    - id: 2
                      name: Chris's Brilliant Club



components:
  schemas:
    RegisterClub:
      type: object
      properties:
        name:
          type: string

    Club:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
