openapi: 3.0.0
info:
  title: Play it with us
  version: 0.1.0

# servers:
#   - url: http://piwu.example.com/
#     description: Production

paths:
  /users:
    post:
      summary: Sign up
      tags: ['Sign-Up']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUp'
      responses:
        200:
          description: OK

  /clubs:
    post:
      summary: Register a new club
      tags: ['Club Directory']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/RegisterClub.schema.yaml'
      responses:
        202:
          description: Accepted

components:
  schemas:
    SignUp:
      type: object
      required:
        - phone
      properties:
        phone:
          type: string
