openapi: 3.0.0
info:
  title: Play it with us
  version: 0.1.0

servers:
  - url: http://piwu.example.com/
    description: Production
paths:
  /clubs:
    get:
      summary: Get all the clubs
      responses:
        200:
          description: A JSON array of clubs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Club'
              examples:
                Tom:
                  value:
                    - id: 1
                      name: Tom's Awesome Club
                    - id: 2
                      name: Tom's Brilliant Club
                Chris:
                  value:
                    - id: 1
                      name: Chris's Awesome Club
                    - id: 2
                      name: Chris's Brilliant Club



components:
  schemas:
    Club:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
