openapi: 3.0.0
info:
  title: Play it with us
  version: 0.1.0

# servers:
#   - url: http://piwu.example.com/
#     description: Production

paths:
  /clubs:
    post:
      summary: Register a new club
      tags: ['Club Directory']
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterClub'
      responses:
        202:
          description: Accepted

components:
  schemas:
    RegisterClub:
      type: object
      required:
        - name
      properties:
        name:
          type: string
