name: 'Netlify Preview Deploy'

on:
  push:
    branches: ['main','deploy-swagger']

jobs:
  deploy-swagger:
    name: 'Deploy Swagger'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

#     - name: Generate Swagger UI
#       uses: Legion2/swagger-ui-action@v1
#       with:
#         output: docs/swagger
#         spec-file: api.yaml

      - name: Copy OAS file to swagger
        run: cp api.yaml docs/swagger

      - name: Make Slate dir
        run: mkdir docs/slate

      - name: Make AsycAPI dir
        run: mkdir docs/asyncapi

      - name: Build markdown
        run: npx widdershins --search false --language_tabs 'shell:cURL' --summary api.yaml -o index.html.md

      - name: Build Slate
        run: docker run --rm -v $(pwd)/docs/slate:/srv/slate/build -v $(pwd)/index.html.md:/srv/slate/source/index.html.md slatedocs/slate build

      - name: Build AsyncAPI docs
        run: docker run --rm -v $(pwd)/docs/asyncapi:/app/example -v $(pwd)/asyncapi.yaml:/app/asyncapi.yaml asyncapi/generator asyncapi.yaml @asyncapi/html-template -o example

      - name: Archive Slate source
        uses: actions/upload-artifact@v3
        with:
          name: slate-source
          path: index.html.md

      - name: Archive Slate build
        uses: actions/upload-artifact@v3
        with:
          name: slate-source
          path: docs/slate

      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          build_directory: docs

