name: 'Netlify Preview Deploy'

on:
  push:
    branches: ['main','deploy-swagger']

jobs:
  deploy-swagger:
    name: 'Deploy Swagger'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Copy api.yaml to Swagger
        run: cp api.yaml docs/swagger/

      - name: Copy static assests for Swagger
        run: |
          docker run \
            --rm \
            -v ${PWD}/docs/swagger/:/dist-local/ \
            --entrypoint cp \
            swaggerapi/swagger-ui \
            /usr/share/nginx/html/swagger-ui.css \
            /usr/share/nginx/html/favicon-32x32.png \
            /usr/share/nginx/html/favicon-16x16.png \
            /usr/share/nginx/html/swagger-ui-bundle.js \
            /usr/share/nginx/html/swagger-ui-standalone-preset.js \
            /dist-local

      - name: Make Slate dir
        run: mkdir docs/slate

      - name: Make AsycAPI dir
        run: mkdir docs/asyncapi

      - name: Build markdown
        run: npx widdershins --search false --language_tabs 'shell:cURL' --summary api.yaml -o index.html.md

      - name: Build Slate
        run: docker run --rm -v $(pwd)/docs/slate:/srv/slate/build -v $(pwd)/index.html.md:/srv/slate/source/index.html.md slatedocs/slate build

      - name: Build AsyncAPI docs
        run: docker run --rm -v $(pwd)/docs/asyncapi:/app/example -v $(pwd)/asyncapi.yaml:/app/asyncapi.yaml asyncapi/generator asyncapi.yaml @asyncapi/html-template -o example

      - name: Archive Slate source
        uses: actions/upload-artifact@v3
        with:
          name: slate-source
          path: index.html.md

      - name: Archive Slate build
        uses: actions/upload-artifact@v3
        with:
          name: slate-source
          path: docs/slate

      - uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          install_command: "echo Skipping installing the dependencies"
          build_command: "echo Skipping building the web files"
          build_directory: docs

